CREATE TABLE groups
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE,
    updated_at           TIMESTAMP WITH TIME ZONE,
    name                 VARCHAR(15)                             NOT NULL,
    description          VARCHAR(100)                            NOT NULL,
    type                 VARCHAR(16)                             NOT NULL,
    capacity             INTEGER                                 NOT NULL,
    recruitment_mode     VARCHAR(16)                             NOT NULL,
    recruitment_start_at TIMESTAMP WITH TIME ZONE,
    recruitment_end_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_groups PRIMARY KEY (id),
    CONSTRAINT uk_groups_name UNIQUE (name),
    CONSTRAINT ck_groups_name CHECK (
        name = BTRIM(name) AND CHAR_LENGTH(name) BETWEEN 1 AND 15
    ),
    CONSTRAINT ck_groups_description CHECK (
        description = BTRIM(description) AND CHAR_LENGTH(description) BETWEEN 1 AND 100
    ),
    CONSTRAINT ck_groups_type CHECK (type IN ('DEPARTMENT', 'STUDY')),
    CONSTRAINT ck_groups_capacity CHECK (capacity BETWEEN 1 AND 50),
    CONSTRAINT ck_groups_recruitment_mode CHECK (recruitment_mode IN ('ALWAYS', 'PERIOD')),
    CONSTRAINT ck_groups_recruitment_period CHECK (
        (
            recruitment_mode = 'ALWAYS'
            AND recruitment_start_at IS NULL
            AND recruitment_end_at IS NULL
        )
        OR
        (
            recruitment_mode = 'PERIOD'
            AND recruitment_start_at IS NOT NULL
            AND recruitment_end_at IS NOT NULL
            AND recruitment_start_at <= recruitment_end_at
        )
    )
);

CREATE TABLE group_member
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    group_id   BIGINT                                 NOT NULL,
    member_id  BIGINT                                 NOT NULL,
    role       VARCHAR(16)                            NOT NULL,
    CONSTRAINT pk_group_member PRIMARY KEY (id),
    CONSTRAINT fk_group_member_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_member_member FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT uk_group_member_group_member UNIQUE (group_id, member_id),
    CONSTRAINT ck_group_member_role CHECK (role IN ('LEADER', 'MEMBER'))
);

CREATE UNIQUE INDEX uk_group_member_single_leader
    ON group_member (group_id)
    WHERE role = 'LEADER';

CREATE INDEX idx_group_member_member_id
    ON group_member (member_id);

CREATE TABLE group_application
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE,
    updated_at   TIMESTAMP WITH TIME ZONE,
    group_id     BIGINT                                 NOT NULL,
    applicant_id BIGINT                                 NOT NULL,
    content      VARCHAR(20)                            NOT NULL,
    status       VARCHAR(16)                            NOT NULL,
    CONSTRAINT pk_group_application PRIMARY KEY (id),
    CONSTRAINT fk_group_application_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_application_applicant FOREIGN KEY (applicant_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT ck_group_application_content CHECK (
        content = BTRIM(content) AND CHAR_LENGTH(content) BETWEEN 1 AND 20
    ),
    CONSTRAINT ck_group_application_status CHECK (
        status IN ('PENDING', 'ACCEPTED', 'REJECTED')
    )
);

CREATE UNIQUE INDEX uk_group_application_pending
    ON group_application (group_id, applicant_id)
    WHERE status = 'PENDING';

CREATE INDEX idx_group_application_group_status_id
    ON group_application (group_id, status, id);

CREATE INDEX idx_group_application_applicant_id
    ON group_application (applicant_id);
